### PR TITLE
Create Population Synthesizer Benchmark

### PR DESCRIPTION
**Pull request by DavidOry**
fyi @lmz, @bstabler

Here's the direction I'm going with the MTC data.

### CODE REVIEW

**Comment by DavidOry** [comment]
@bstabler
Beta version is ready for your review. Intent is to include only the PUMS variables and the variables needed for the expansion and to line up variable names in a cleaner way. A bit of work would be needed to manipulate these files back into PopulationSim inputs, but the `controls.csv` file should be simpler.

**Comment by bstabler** [comment]
@DavidOry - I plan to run this example once we release the PopSim multiprocess version - https://github.com/ActivitySim/populationsim/pull/130

**Comment by lmz** [comment]
Hi @DavidOry - Coming back to this, it looks like there's a version of the updated data files in this dir: https://github.com/ZephyrTransport/software-badging-benchmarks/tree/develop-pop-syn/population-synthesis/san-francisco-bay-area 
as well as in 
https://github.com/ZephyrTransport/software-badging-benchmarks/tree/develop-pop-syn/population-synthesis/san-francisco-bay-area/scripts

Is this intentional?  The latter files look a little bit more recent since they were updated in this commit: https://github.com/ZephyrTransport/software-badging-benchmarks/commit/2980828e1241a8017fde2ade111ad3e442f7b2c3

I would think we'd want one version of these and not in the scripts folder?

**Comment by DavidOry** [comment]
> Hi @DavidOry - Coming back to this, it looks like there's a version of the updated data files in this dir: https://github.com/ZephyrTransport/software-badging-benchmarks/tree/develop-pop-syn/population-synthesis/san-francisco-bay-area
> as well as in
> https://github.com/ZephyrTransport/software-badging-benchmarks/tree/develop-pop-syn/population-synthesis/san-francisco-bay-area/scripts
> 
> Is this intentional? The latter files look a little bit more recent since they were updated in this commit: [2980828](https://github.com/ZephyrTransport/software-badging-benchmarks/commit/2980828e1241a8017fde2ade111ad3e442f7b2c3)
> 
> I would think we'd want one version of these and not in the scripts folder?

Agree. Unintentional and has been [corrected](https://github.com/ZephyrTransport/software-badging-benchmarks/commit/f8d7c46177eeda71403f109c30c6183b1b8f231d).

**Pull request merged**
